
GET http://localhost:4001/api/instanciasdiplomado/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjI3MzhlNmI0OWY2MzFkODY1ZTY1NiIsImlhdCI6MTYxNzkyMTczOSwiZXhwIjoxNjE4MDA4MTM5fQ.FigtaJiRxxcUGaV3HHWFP-sr7U8HoQxPm8fOCKAjzuA

###

POST http://localhost:4001/api/instanciasdiplomado
Content-Type: application/json

{
  "diplomado": "606262bbacf17d23e6fb6d79",
  "fecha": {
    "inicio": "2021-03-19T01:22:06.208Z",
    "fin": "2021-03-19T01:22:06.208Z"
  },
  "inscritos": [],
  "aprobados": [],
  "reprobados": []
}

###

DELETE http://localhost:4001/api/instanciasdiplomado


###

PUT http://localhost:4001/api/instanciasdiplomado/606cc541e2f587247ed07d6b
Content-Type: application/json

{
  "curso": "60625e909696201b7c758824",
  "fecha": {
    "inicio": "2021-03-19T01:22:06.208Z",
    "fin": "2021-03-19T01:22:06.208Z"
  },
  "inscritos": [],
  "aprobados": [],
  "reprobados": []
}

