
GET http://localhost:4001/api/instanciascurso/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzFkZTYzZmFiMGY5MTkzN2JlODRmZSIsImlhdCI6MTYxODM0MjMzNCwiZXhwIjoxNjE4NDI4NzM0fQ.3s2tVwjluzSKVtWp9SPo4mvNxuNLC8M0fAWAXEzOarM

###

POST http://localhost:4001/api/instanciascurso
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzFkZTYzZmFiMGY5MTkzN2JlODRmZSIsImlhdCI6MTYxODA4MzIxNCwiZXhwIjoxNjE4MTY5NjE0fQ.yKA7suQeGGflbFHWw1pf9Kg7GP9v_tiY9UpC1P-O_9Q
Content-Type: application/json

{
  "curso": "606cc5a0e2f587247ed07d6d",
  "tutor": "6071dea1fab0f91937be8500",
  "fecha": {
    "inicio": "2021-03-19T01:22:06.208Z",
    "fin": "2021-03-19T01:22:06.208Z"
  },
  "inscritos": [],
  "aprobados": [],
  "reprobados": []
}

###

DELETE http://localhost:4001/api/instanciascurso


###

PUT http://localhost:4001/api/instanciascurso/6071fdcd9d153e2ae2062472
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzFkZTYzZmFiMGY5MTkzN2JlODRmZSIsImlhdCI6MTYxODA4MzIxNCwiZXhwIjoxNjE4MTY5NjE0fQ.yKA7suQeGGflbFHWw1pf9Kg7GP9v_tiY9UpC1P-O_9Q
Content-Type: application/json

{
  "curso": "606cc5a0e2f587247ed07d6d",
  "tutor": null,
  "fecha": {
    "inicio": "2021-08-19T01:22:06.208Z",
    "fin": "2021-03-19T01:22:06.208Z"
  },
  "inscritos": [],
  "aprobados": [],
  "reprobados": []
}
