GET http://localhost:4001/api/areas/

###

POST http://localhost:4001/api/areas
Content-Type: application/json

{
  "area": "Test 4"
}

###

DELETE http://localhost:4001/api/areas/605e52305fce88256922cc86


###

PUT http://localhost:4001/api/areas/605e51445fce88256922cc85
Content-Type: application/json

{
  "area": "Test siete"
}


###

DELETE http://localhost:4001/api/areas/6053d12b3fb19646bea82489


###
