
GET http://localhost:4001/api/usuarios/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzFkZTYzZmFiMGY5MTkzN2JlODRmZSIsImlhdCI6MTYxODA4MTMxMSwiZXhwIjoxNjE4MTY3NzExfQ.Ts0BTj_HBoI1KFJAAahBncFeQIo4O9y8sFSh6pkw3Rc

###

POST http://localhost:4001/api/usuarios
Content-Type: application/json

{
  "nombre": {
    "primero": "Alejandro"
  },
  "apellido": {
    "paterno": "Larraga",
    "materno": "Gonzalez"
  },
  "fecha": {
    "nacimiento": "2021-03-19T01:22:06.208Z",
    "ingreso": "2021-03-19T01:22:06.208Z"
  },
  "areas": {
    "docente": [],
    "coach": ["606271c8ae41c02e8970ed47"]
  },
  "roles": ["coach"],
  "matricula": "179999",
  "clave": "179999"
}

###

PUT http://localhost:4001/api/usuarios/606274befc38be3465ff0ed4
Content-Type: application/json

{
  "nombre": {
    "primero": "Alejandro",
    "segundo": "Emmet"
  },
  "apellido": {
    "paterno": "Larraga",
    "materno": "Gonzalez"
  },
  "fecha": {
    "nacimiento": "2021-03-19T01:22:06.208Z",
    "ingreso": "2021-03-19T01:22:06.208Z"
  },
  "areas": {
    "docente": [],
    "coach": ["606271c8ae41c02e8970ed47"]
  },
  "roles": ["coach"],
  "matricula": 179999,
  "clave": "179999",
  "id": "60540f4facaab98d309a6721"
}


###

DELETE http://localhost:4001/api/usuarios/606a6f4822a8e167afd4b383
